services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    working_dir: /docker/database
    networks:
      - hono-app-network
    ports:
      - "5432:5432"
    volumes:
      - ./docker/database/backup:/app/database
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=GMT-3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app-database

  # hono-app:
  #   build: .
  #   container_name: hono-app
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   networks:
  #     - hono-app-network

volumes:
  postgres-data:

networks:
  hono-app-network:
    driver: bridge
    name: hono-app-network
